---
# Copyright (C) 2021-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Downloading runc
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: "{{ runc_bin_directory }}/runc"
    checksum: "{{ runc_checksum }}"
    mode: "{{ runc_binary_mode }}"
    owner: "{{ runc_owner | default(omit) }}"
    group: "{{ runc_group | default(omit) }}"
  tags:
    - runc-download
